// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"N_WeatherFog","status":true,"description":"雾天气效果","parameters":{"fogQuality":"4","fogSpeed":"0.25","xScale":"400","yScale":"150"}}
];
